# Generated by Django 5.2.14 on 2026-06-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
