# Generated by Django 5.2.14 on 2026-06-09 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissionnaires', '0001_initial'),
        ('listings', '0002_listing_availability_changed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acquisition_context', models.JSONField(blank=True, default=dict)),
                ('commissionnaire_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='commissionnaires.commissionnaireprofile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='listings.listing')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('closed', 'Fermé')], default='new', max_length=32)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='leads.lead')),
            ],
            options={
                'ordering': ['-changed_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstatusevent',
            index=models.Index(fields=['status'], name='leads_leads_status_1f08b4_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstatusevent',
            index=models.Index(fields=['changed_at'], name='leads_leads_changed_402228_idx'),
        ),
    ]
