# Generated by Django 5.2.14 on 2026-06-10 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppHandoffAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoff_attempts', to='leads.lead')),
            ],
            options={
                'ordering': ['-attempted_at', 'id'],
                'indexes': [models.Index(fields=['attempted_at'], name='leads_whats_attempt_37554f_idx')],
            },
        ),
    ]
