# Generated by Django 5.2.14 on 2026-06-07 21:48

import apps.listings.models
import apps.listings.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price_amount', models.PositiveIntegerField()),
                ('monthly_price_currency', models.CharField(choices=[('USD', 'USD')], default='USD', max_length=3)),
                ('commune', models.CharField(max_length=120)),
                ('bedroom_count', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('under_review', 'Under review')], default='under_review', max_length=32)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commissionnaire_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='commissionnaires.commissionnaireprofile')),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.listings.models.listing_photo_upload_to, validators=[apps.listings.validators.validate_listing_photo_upload])),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['availability_status', '-updated_at'], name='listing_status_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['commune'], name='listing_commune_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['bedroom_count'], name='listing_bedrooms_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['monthly_price_amount'], name='listing_price_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingphoto',
            constraint=models.UniqueConstraint(fields=('listing', 'position'), name='unique_listing_photo_position'),
        ),
        migrations.AddConstraint(
            model_name='listingphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('listing',), name='unique_primary_photo_per_listing'),
        ),
    ]
