# Generated by Django 5.2.14 on 2026-06-09 10:36

import django.utils.timezone
from django.db import migrations, models


def backfill_availability_timestamps(apps, schema_editor):
    from django.utils import timezone
    Listing = apps.get_model('listings', 'Listing')
    for listing in Listing.objects.all():
        timestamp = listing.submitted_at or listing.updated_at or timezone.now()
        listing.availability_changed_at = timestamp
        listing.availability_reconfirmed_at = timestamp
        listing.save(update_fields=['availability_changed_at', 'availability_reconfirmed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('commissionnaires', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='availability_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='availability_reconfirmed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill_availability_timestamps, reverse_code=migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['availability_status', '-availability_reconfirmed_at'], name='listing_status_reconfirmed_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['availability_status', '-availability_changed_at'], name='listing_status_changed_idx'),
        ),
    ]
