# Generated by Django 5.2.14 on 2026-06-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissionnaires', '0001_initial'),
        ('listings', '0002_listing_availability_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathroom_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Appartement'), ('house', 'Maison'), ('studio', 'Studio'), ('room', 'Chambre'), ('other', 'Autre')], default='apartment', max_length=32),
        ),
        migrations.AddField(
            model_name='listing',
            name='verification_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['property_type'], name='listing_type_idx'),
        ),
    ]
