# Generated by Django 5.2.14 on 2026-06-09 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', 'id'],
                'indexes': [models.Index(fields=['event_type'], name='audit_audit_event_t_04511c_idx'), models.Index(fields=['target_id'], name='audit_audit_target__8d9a07_idx'), models.Index(fields=['timestamp'], name='audit_audit_timesta_ee9c56_idx')],
            },
        ),
    ]
