# Generated by Django 5.2.14 on 2026-06-07 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionnaireProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('whatsapp_phone', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commissionnaire_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commissionnaire profile',
                'verbose_name_plural': 'Commissionnaire profiles',
                'ordering': ['display_name', 'id'],
            },
        ),
    ]
